home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('friendlist/', views.friendlist, name='friendlist'),
]

story4ppw/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

class Year(models.Model):
    yearof = (("2019", "Maung (2019)"), ("2018", "Quanta (2018)"), ("2017", "Tarung (2017)"), ("2016", "Omega (2016)"), ("Alumni", "Alumni (2015—)"))
    year = models.CharField(choices=yearof, default="2019", null=True, max_length=6)
    
    def __str__(self):
        return self.year

class DataField(models.Model):
    # auto_increment_id = models.AutoField(primary_key=True)
    firstname = models.CharField(max_length=200, null=True)
    lastname = models.CharField(max_length=200, null=True)
    theyearof = (("2019", "Maung (2019)"), ("2018", "Quanta (2018)"), ("2017", "Tarung (2017)"), ("2016", "Omega (2016)"), ("Alumni", "Alumni (2015—)"))
    hobby = models.CharField(max_length=200, null=True)
    fnb = models.CharField(max_length=200, null=True)
    theyear = models.CharField(choices=theyearof, default="2019", null=True, max_length=6)

    def __str__(self):
        return self.firstname

# class Post(models.Model):
#     content = models.CharField(null=True)
#     published_data = models.DateTimeField(default=timezone.now)

story4app/models.py
# from django.db import models
# from django.utils import timezone
# from datetime import datetime, date

# class DataField(models.Model):
#     firstname = models.CharField(max_length=300, unique=True)
#     lastname = models.CharField(max_length=300, unique=True)
#     email = models.CharField(max_length=300, unique=True)
#     subject = models.TextField()

#     def __str__(self):
#         return '%s' % self.name

# class Post(models.Model):
#     author = models.ForeignKey(DataField, on_delete = models.CASCADE)
#     content = models.CharField(max_length=300)
#     published_data = models.DateTimeField(default=timezone.now)

home/forms.py
from django.forms import ModelForm
from .models import DataField, Year

class DataFieldForm(ModelForm):
    class Meta:
        model = DataField
        fields = "__all__"

home/views.py
from .models import DataField
from .forms import DataFieldForm
from django.shortcuts import render
from . import forms

def home(request):
    return render(request, 'home/testhome.html')

def about(request):
    return render(request, 'home/testabout.html')

def contact(request):
    if request.method == 'POST':
        form = DataFieldForm(request.POST)
        if form.is_valid():
            # data_item = form.save(commit=False)
            # data_item.save()
            form.save()
            return render(request, 'home/testthx.html')

    else:
        form = DataFieldForm()
        return render(request, 'home/testcontact.html', {'form': form})

    
def portfolio(request):
    return render(request, 'home/testporto.html')

def friendlist(request):
    # form = DataFieldForm(request.POST)
    friendlist = DataField.objects.all()
    return render(request, 'home/testlist.html', {'friendlist': friendlist})

# def add_data(request):
#     if request.method == 'POST':
#         if form.is_valid():
#             blog_item = form.save(commit=False)
#             blog_item.save()
    

story4app/views.py
# from django.core.mail import send_mail, BadHeaderError
# from django.http import HttpResponse, HttpResponseRedirect
# from django.shortcuts import render, redirect
# from story4ppw.forms import PostForm

# def PostView(request):
#     if request.method == 'GET':
#         form = PostForm()
#     else:
#         form = PostForm(request.POST)
#         if form.is_valid():
#             firstname = form.cleaned_data['firstname']
#             lastname = form.cleaned_data['lastname']
#             email = form.cleaned_data['email']
#             subject = form.cleaned_data['subject']
#             try:
#                 send_mail(subject, email, ['admin@example.com'])
#             except BadHeaderError:
#                 return HttpResponse('Invalid header found.')
#             return redirect('success')
#     return render(request, "contact.html", {'form': form})

# def successView(request):
#     return HttpResponse('Success! Thank you for your message.')

home/templates/home/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/styles.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <title>Hanifah Annisa Putri</title>
  </head>
  <body style="background-color: black;">

      <h1 style="padding: 21px; font-size: larger; padding-bottom: 0%;">Hanifah Annisa Putri</h1>
        <h2 style="font-size: small; padding: 23px; padding-top: 0%; padding-bottom: 0%">I wanted to be your tomorrow, so I lived today.</h2>
        <hr>
    <nav class="navbar navbar-expand-lg navbar-light navbar-custom" style="padding-top: 0px;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'home:home' %}">home</a>
            <a class="nav-item nav-link" href="{% url 'home:about' %}">about <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'home:contact' %}">contact</a>
            <a class="nav-item nav-link" href="{% url 'home:portfolio' %}">portfolio</a>
            <a class="nav-item nav-link" href="{% url 'home:friendlist' %}">friendlist</a>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  socials
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="background-color: black;">
                  <a class="dropdown-item" href="http://instagram.com/hanifahanns">instagram</a>
                  <a class="dropdown-item" href="mailto:hanifahaputri@gmail.com?subject=Hello">gmail</a>
                </div>
              </li>
        </div>
      </nav>
    </body>

    {%block content%}{% endblock %}

    <p style="text-align: center;">Copyright Hanifah Annisa Putri 2020.</p>

        <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script type="text/javascript" src="{% static 'home/js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'home/js/popper.js' %}"></script>
    <script type="text/javascript" src="{%static 'home/js/bootstrap.min.js' %}"></script>
  </body>
</html>

home/templates/home/testabout.html
{% extends "home/base.html"%}
{% load static %}
{% block content %}
      <div id="box">
          <div id="boxlagi">
            <h1 style="font-weight: 100; font-size:200%; text-align: left; padding-left: 1.5%;">about</h1>
            <hr>
            <h3 style="font-size:medium; line-height: 185%; padding: 1.5%; text-align: left;">Hello! My name is Hanifah Annisa Putri, I am an eighteen years old Computer Science student at University of Indonesia class of 2019. I have an interest towards illustrating, design, and things related to creating, which often makes me involved in events as a comittee in the departments related to design. I also have an interest on creating merchandise or souvenirs which I sometimes make to add some money on my allowance.</h3>
            </div>
      </div>
      <p></p>
      <a href="http://www.instagram.com/hanifahanns"><img src="https://i.pinimg.com/originals/63/9b/3d/639b3dafb544d6f061fcddd2d6686ddb.png" alt="ig logo" width="48" height="36" class="center"></a>

{% endblock %}

home/templates/home/testcontact.html
{% extends "home/base.html"%}
{% load static %}
{% block content %}

    <div id="box" style="padding: 2%; padding-top: 2%;">
        <div id="boxlagi">
    <h2 style="text-align: center; color: #CCB096 !important;">contact</h2>
    <div class="container; text:center" style="position:relative">
        <form action="" method="POST">
          {% csrf_token %}
          <div class="text-align:center">
            <h3 style="font-size: medium; padding: 0.5%;">First Name<br>{{ form.firstname }}</h3>
            <h3 style="font-size: medium; padding: 0.5%;">Last Name<br>{{ form.lastname }}</h3>
            <h3 style="font-size: medium; padding: 0px">Year Of<br>{{ form.theyear }}</h3>
            <h3 style="font-size: medium; padding: 0px;">Hobby<br>{{ form.hobby }}</h3>
            <h3 style="font-size: medium; padding: 0px;">Food and Beverage<br>{{ form.fnb }}</h3>
          </div>
          <!-- <label for="fname">First Name</label><br>
          <input type="text" id="fname" name="firstname" placeholder=" John" style="color: #E7D6C6;"><br>
      
          <label for="lname">Last Name</label><br>
          <input type="text" id="lname" name="lastname" placeholder=" Doe" style="color: #E7D6C6;"><br>
          
          <label for="lname">Email</label><br>
          <input type="text" id="email" name="email" placeholder=" john.doe@mail.com" style="color: #E7D6C6;"><br>
      
          <label for="subject">Message</label><br>
          <textarea id="subject" name="subject" placeholder=" Your message here..." style="height:100px; color: #E7D6C6;"></textarea><br>
       -->
          <input type="submit" value="Save">
      
        </form>
        <br>
        <a href="{% url 'home:friendlist' %}" style="color: beige; font-style: italic;">Friendlist</a>
        </div>
      </div>
      </div>
      <br>
      <a href="http://www.instagram.com/hanifahanns"><img src="https://i.pinimg.com/originals/63/9b/3d/639b3dafb544d6f061fcddd2d6686ddb.png" alt="ig logo" width="48" height="36" class="center"></a>

{% endblock %}

home/templates/home/testhome.html
{% extends "home/base.html"%}
{% load static %}
{% block content %}


      <div id="box">
          <div id="boxlagi">
            <h1 style="font-weight: 100; font-size:700%; text-align: center; padding-top:1%">welcome</h1>
            <h1 style="font-size:larger; line-height: 0%; padding-bottom: 1%; text-align: center;">have a wonderful stay.</h1>
            <br>
            <a href="{% url 'home:about' %}" class="btn btn-primary active" role="button" aria-pressed="true">explore</a>
          </div>
      </div>
      <p></p>
      <a href="http://www.instagram.com/hanifahanns"><img src="https://i.pinimg.com/originals/63/9b/3d/639b3dafb544d6f061fcddd2d6686ddb.png" alt="ig logo" width="48" height="36" class="center"></a>



      {% endblock %}

home/templates/home/testlist.html
{% extends "home/base.html"%}
{% load static %}
{% block content %}

      <div id="box">
          <div id="boxlagi">
            <h1 style="font-weight: 100; font-size:200%; text-align: left; padding-left: 1.5%;">friend list</h1>
            <h3 style="font-size:medium; line-height: 0%; padding-left: 1.5%; text-align: left;">Here's a list of my friends</h3>
            <hr>
            <div align="center" style="text-align:center">
            <table style="border-color: #CCB096; text-align: center;" border="5%" width="100%">
                  <tr style="text-align: center;">
                        <th style="text-align: center;">First Name</th>
                        <th style="text-align: center;">Last Name</th>
                        <th style="text-align: center;">Year Of</th>
                        <th style="text-align: center;">Hobby</th>
                        <th style="text-align: center;">Food and Beverage</th>
                  </tr>
                  {% for form in friendlist %}
                  <tr>
                        <td>{{form.firstname}}</td>
                        <td>{{form.lastname}}</td>
                        <td>{{form.theyear}}</td>
                        <td>{{form.hobby}}</td>
                        <td>{{form.fnb}}</td>
                  </tr>
                  {% endfor %}
            </table>
            <br>
            <a href="{% url 'home:contact' %}" class="btn btn-primary active" role="button" aria-pressed="true">become my friend</a>       
      </div>
      </div>   
      </div>
      <p></p>
      <a href="http://www.instagram.com/hanifahanns"><img src="https://i.pinimg.com/originals/63/9b/3d/639b3dafb544d6f061fcddd2d6686ddb.png" alt="ig logo" width="48" height="36" class="center"></a>

{% endblock %}

home/templates/home/testporto.html
{% extends "home/base.html"%}
{% load static %}
{% block content %}

    <h1 style="background-color: transparent; text-align: center; font-size: xx-large;">portfolio</h2><br>
<div class="container">
  <div class="row">
    <div class="col-md-4">
        <div class="thumbnail" style="background-color: transparent; border-color: #E7D6C6;">
        <a href="https://pbs.twimg.com/media/EQdr_FRUcAAIrbk?format=jpg&name=4096x4096" target="_blank">
            <img src="https://pbs.twimg.com/media/EQdr_FRUcAAIrbk?format=jpg&name=4096x4096" alt="Nature" style="width:100%;">
            <div class="caption">
            <p>Lorem ipsum donec id elit non mi porta gravida at eget metus.</p>
          </div>
        </a>
      </div>
    </div>
        <div class="col-md-4">
        <div class="thumbnail" style="background-color: transparent; border-color: #E7D6C6;">
            <a href="https://pbs.twimg.com/media/EQdr_FdUwAAFjKI?format=jpg&name=4096x4096" target="_blank">
            <img src="https://pbs.twimg.com/media/EQdr_FdUwAAFjKI?format=jpg&name=4096x4096" alt="Nature" style="width:100%;">
            <div class="caption">
                <p>Lorem ipsum donec id elit non mi porta gravida at eget metus.</p>
            </div>
            </a>
        </div>
        </div>
        <div class="col-md-4">
            <div class="thumbnail" style="background-color: transparent; border-color: #E7D6C6;">
            <a href="https://pbs.twimg.com/media/EQdueobUwAEDg7K?format=jpg&name=4096x4096" target="_blank">
                <img src="https://pbs.twimg.com/media/EQdueobUwAEDg7K?format=jpg&name=4096x4096" alt="Nature" style="width:100%;">
                <div class="caption">
                <p>Lorem ipsum donec id elit non mi porta gravida at eget metus.</p>
            </div>
            </a>
        </div>
        </div>
        <div class="col-md-4">
            <div class="thumbnail" style="background-color: transparent; border-color: #E7D6C6;">
            <a href="https://pbs.twimg.com/media/EQdueoNU8AArnN8?format=jpg&name=4096x4096" target="_blank">
                <img src="https://pbs.twimg.com/media/EQdueoNU8AArnN8?format=jpg&name=4096x4096" alt="Nature" style="width:100%;">
                <div class="caption">
                <p>Lorem ipsum donec id elit non mi porta gravida at eget metus.</p>
            </div>
            </a>
        </div>
        </div>
        <div class="col-md-4">
            <div class="thumbnail" style="background-color: transparent; border-color: #E7D6C6;">
            <a href="https://pbs.twimg.com/media/EQdueoAUUAABRmP?format=jpg&name=4096x4096" target="_blank">
                <img src="https://pbs.twimg.com/media/EQdueoAUUAABRmP?format=jpg&name=4096x4096" alt="Nature" style="width:100%;">
                <div class="caption">
                <p>Lorem ipsum donec id elit non mi porta gravida at eget metus.</p>
            </div>
            </a>
        </div>
        </div>
        <div class="col-md-4">
            <div class="thumbnail" style="background-color: transparent; border-color: #E7D6C6;">
            <a href="https://pbs.twimg.com/media/EQdsGKLU8AUjWMm?format=jpg&name=4096x4096" target="_blank">
                <img src="https://pbs.twimg.com/media/EQdsGKLU8AUjWMm?format=jpg&name=4096x4096" alt="Nature" style="width:100%;">
                <div class="caption">
                <p>Lorem ipsum donec id elit non mi porta gravida at eget metus.</p>
            </div>
            </a>
        </div>
        </div>
        </div>
          <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
          More...
        </button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel" style="font-size: larger;">You have reached the end!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                You have reached the end of the portfolio page. Please anticipate for more works by me. Thank you for your attention, have a great day!
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">close</button>
              </div>
            </div>
          </div>
        </div>
        <p></p>
        <div class="center">
          <a href="http://www.instagram.com/hanifahanns"><img src="https://i.pinimg.com/originals/63/9b/3d/639b3dafb544d6f061fcddd2d6686ddb.png" alt="ig logo" width="48" height="36" class="center"></a>
        </div>


{% endblock %}

home/templates/home/testthx.html
{% extends "home/base.html"%}
{% load static %}
{% block content %}


      <div id="box">
          <div id="boxlagi">
            <h1 style="font-weight: 100; font-size:500%; text-align: center; padding-top:1%">thank you</h1>
            <hr>
            <p>thank you for filling out the form.</p>
            </div>
      </div>
      <p></p>
      <a href="http://www.instagram.com/hanifahanns"><img src="https://i.pinimg.com/originals/63/9b/3d/639b3dafb544d6f061fcddd2d6686ddb.png" alt="ig logo" width="48" height="36" class="center"></a>



      {% endblock %}